Fix wrongful inclusion of Adafruit nRFCrypto library
adafruit/Adafruit_nRF52_Arduino pull request #738
Opened 2022-07-08 15:08 UTC by maxgerhardt

Fixes https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/737

I still have to test this..

2022-07-09 20:35 UTC, ladyada commented
we really really do not want to do this, then we have to maintain two library files.

@ivankravets is there a way to fix this so platformio stops misparsing C files, maybe a different preparser? this issue keeps coming up where valid C code that has ifdefs doesnt work with platformio. or have some inline alert to tell platformio. thank you!

2022-07-09 20:36 UTC, ladyada requested changes
we do not want two places that need version updates

2022-07-09 20:37 UTC, maxgerhardt commented
I understand that two version fields is bad -- but I still wanted to try to just have
```json
{
  "build":
  {
    "libLDFMode": "chain+"
  }
}
```
so that.. maybe.. PlatformIO gets version info from `library.properties` and this critical build info from the `library.json`, hence no double version maintaining.

2022-07-10 17:08 UTC, ladyada commented
yes that would be ideal... or have some extra line in the library.properties file

2022-07-11 10:10 UTC, ivankravets commented
PlatformIO Core already enables "Arduino Preprocessing" for a library if it has a `depends` field. The problem is linked with the version of this Arduino Core that is hosted in our registry. It has patched libraries. See the contents of `~/.platformio/packages/framework-arduinoadafruitnrf52/libraries/Bluefruit52Lib`.

@maxgerhardt, please move this issue to https://github.com/platformio/platform-nordicnrf52/issues

P.S: See `~/.platformio/packages/framework-arduinoadafruitnrf52/libraries/Bluefruit52Lib/extra_script.py`:

```python

# The only purpose of this extra script is to set the `NRF_CRYPTOCELL` macro for the
# nrf52840 series because the original `NRF_CRYPTOCELL` macro is set in the framework
# sources and not visible when PlatformIO LDF resolves dependencies.
if env.BoardConfig().get("build.mcu", "").startswith("nrf5284"):
    env.Append(
        CPPDEFINES=[("NRF_CRYPTOCELL", "((NRF_CRYPTOCELL_Type*) NRF_CRYPTOCELL_BASE)")],

    )
```

2022-07-11 12:08 UTC, closed without merging